name: Kernel Config - A14 6.1

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs: { }

jobs:
  build-kernels-a14-6-1:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "124"
            os_patch_level: "2025-02"
          #  - sub_level: "128"
          #    os_patch_level: "2025-03"
          #  - sub_level: "129"
          #    os_patch_level: "2025-04"
          #  - sub_level: "134"
          #    os_patch_level: "2025-05"
          #  - sub_level: "138"
          #    os_patch_level: "2025-06"
          #  - sub_level: "141"
          #    os_patch_level: "2025-07"
          #  - sub_level: "145"
          #    os_patch_level: "2025-08"
          #  - sub_level: "145"
          #    os_patch_level: "2025-09"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
